[project]
name = "persistent-wlr-randr-ui"
requires-python   = ">= 3.13.5"
description = "A tiny GUI to configure screen layouts on wlroots and smithay based compositors"
authors = [{ name = "Alice Alysia" }]
urls ={ homepage = "https://github.com/alicealysia/persistent-wlr-randr-gui" }
version = "2.0.0a"
readme = "README.md"
license = "MIT"
scripts = { wlrlui = 'wlr_layout_ui:main' }
dependencies = [
    "pyglet >= 2.1.6",
    "tomli >= 2.2.1",
    "tomli-w >= 1.2.0"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "wlr_layout_ui", from = "src"}]

[tool.poetry.group.dev.dependencies]
mypy = "^1.17.0"
vulture = "^2.14"
pydantic = "^2.11.7"
black = "^25.1.0"

[tool.ruff]
line-length = 140
preview = true

exclude = ["*_v?.py", "tests", "scripts", "sample_extension", ".git"]

[tool.ruff.lint]
fixable = ["ALL"]
select = [
    # pycodestyle
    "E", # error
    "W", # warn
    # builtins
    "A",
    # bugbear
    "B",
    # comprehensions
    "C",
    # err msg
    "EM",
    # str concat
    "ISC",
    # import conventions
    "ICN",
    # flake8 log
    "G",
    "LOG",
    # pep8 naming
    "D",
    # pydocstyle
    "D",
    # mccabe
    "C",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake-2020
    "YTT",
    # flake-annotations
    "ANN",
    # flake-async
    "ASYNC",
    # flake-blind-except
    "BLE",
    # flake-boolean-trap
    "FBT",
    # pytest
    "PT",
    # self
    "SLF",
    # tidy-imports
    "TID",
    # unused arg
    "ARG",
    # pathlib
    "PTH",
    # pylint
    "PL",
    # perflnt
    "PERF",
    # ruf
    "RUF",
]
ignore = ["ANN201", "ANN001", "ANN002", "ANN202", "ARG002", "PLR", "C", "FBT002", "D107", "ANN204", "D", "ISC001"]

[tool.ruff.format]
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint.pydocstyle]
convention = "google"
